apiVersion: skaffold/v2alpha3
kind: Config
deploy : 
  kubectl :
    manifests:
      - ./infra/k8s/*
build :
  # local : 
  #   push : false
  googleCloudBuild :
    projectId: ticket-dev-340116
  artifacts:
    - image: us.gcr.io/ticket-dev-340116/auth
      context: auth
      docker:
        dockerfile : Dockerfile
      sync :
        manual :
          - src: 'src/**/*.ts'
            dest: . 
    - image: us.gcr.io/ticket-dev-340116/client
      context: client
      docker:
        dockerfile : Dockerfile
      sync :
        manual :
          - src: '**/*.js'
            dest: .
    - image: us.gcr.io/ticket-dev-340116/tickets
      context: tickets
      docker:
        dockerfile : Dockerfile
      sync :
        manual :
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticket-dev-340116/orders
      context: orders
      docker:
        dockerfile : Dockerfile
      sync :
        manual :
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticket-dev-340116/payment
      context: payment
      docker:
        dockerfile : Dockerfile
      sync :
        manual :
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticket-dev-340116/expiration
      context: expiration
      docker:
        dockerfile : Dockerfile
      sync :
        manual :
          - src: 'src/**/*.ts'
            dest: .